"""Write a provenance manifest tying results to an exact data + code version.

Produces:
  - data/raw/data_imdc_2026/CHECKSUMS.sha256  (hash of every raw input file)
  - RESULTS.md  (git commit, data-hash summary, timestamp, current leaderboards)

Run as: python scripts/make_manifest.py
"""
import hashlib
import subprocess
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
RAW = ROOT / "data" / "raw" / "data_imdc_2026"
METRICS = ROOT / "results" / "metrics"


def sha256(path: Path, chunk: int = 1 << 20) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for block in iter(lambda: f.read(chunk), b""):
            h.update(block)
    return h.hexdigest()


def git(*args) -> str:
    return subprocess.run(["git", *args], capture_output=True, text=True, cwd=ROOT).stdout.strip()


def write_checksums() -> list:
    rows = []
    for p in sorted(RAW.glob("*")):
        if p.name == "CHECKSUMS.sha256" or not p.is_file():
            continue
        rows.append((sha256(p), p.name, p.stat().st_size))
    out = RAW / "CHECKSUMS.sha256"
    out.write_text("\n".join(f"{h}  {name}  ({size} bytes)" for h, name, size in rows) + "\n")
    return rows


def _leaderboard_md(csv: Path, title: str) -> str:
    if not csv.exists():
        return ""
    df = pd.read_csv(csv)
    df = df.sort_values("wis") if "wis" in df.columns else df
    return f"\n### {title}\n\n" + df.round(2).to_markdown(index=False) + "\n"


def main():
    rows = write_checksums()
    combined_hash = hashlib.sha256("".join(sorted(h for h, _, _ in rows)).encode()).hexdigest()[:16]

    commit = git("rev-parse", "HEAD")
    dirty = "DIRTY" if git("status", "--porcelain") else "clean"
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    md = [
        "# Results provenance\n",
        "*Auto-generated by `scripts/make_manifest.py` — do not edit by hand.*\n",
        f"- **Git commit:** `{commit}` ({dirty})",
        f"- **Raw-data fingerprint:** `{combined_hash}` (SHA-256 of the {len(rows)} input files; "
        "see `data/raw/data_imdc_2026/CHECKSUMS.sha256`)",
        f"- **Generated:** {now}\n",
        "These leaderboards were produced by the pipeline at the commit above from the data "
        "fingerprinted above. Re-run `make reproduce` to regenerate; the deterministic models "
        "(baselines, LightGBM, mechanistic) reproduce bit-for-bit, the GRU up to Apple-MPS "
        "float non-determinism (bit-reproducible on CPU).\n",
    ]
    md.append(_leaderboard_md(METRICS / "final_leaderboard.csv", "Dengue, state level (mean WIS)"))
    md.append(_leaderboard_md(METRICS / "chik_final_leaderboard.csv", "Chikungunya, state level (mean WIS)"))

    (ROOT / "RESULTS.md").write_text("\n".join(md))
    print(f"Wrote CHECKSUMS.sha256 ({len(rows)} files), data fingerprint {combined_hash}, and RESULTS.md")


if __name__ == "__main__":
    main()
